# Permalinks
permalink:           pretty

# Setup
title:               Shikhar Jaiswal
tagline:             ': Thoughtful Algorist'
description:         'Programming · Books · Food'
url:                 https://shikharj.github.io/
paginate:            5

author:
  name:              Shikhar Jaiswal

# Contact Details
contact:
  github:            https://github.com/ShikharJ
  email:             jaiswalshikhar87@gmail.com

# Custom vars
version:             1.0.0
